/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 4.1d1 */
public interface ParserTreeConstants
{
  public int JJTPROG = 0;
  public int JJTDCL = 1;
  public int JJTSTMT = 2;
  public int JJTVAL = 3;
  public int JJTIFEXPR = 4;
  public int JJTEXPR = 5;
  public int JJTEND_OF_FILE = 6;


  public String[] jjtNodeName = {
    "prog",
    "dcl",
    "stmt",
    "val",
    "ifexpr",
    "expr",
    "end_of_file",
  };
}
/* JavaCC - OriginalChecksum=603a7c7d40b9bd9625239f815b8f5f30 (do not edit this line) */
