/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 4.1d1 */
public interface ParserTreeConstants
{
  public int JJTPROG = 0;
  public int JJTDCL = 1;
  public int JJTSTMT = 2;
  public int JJTVAL = 3;
  public int JJTEXPR = 4;


  public String[] jjtNodeName = {
    "prog",
    "dcl",
    "stmt",
    "val",
    "expr",
  };
}
/* JavaCC - OriginalChecksum=78c685bcff92028a8d0b2383180d532c (do not edit this line) */
