/* Compiler.java */
/* Generated By:JavaCC: Do not edit this line. Compiler.java */
import AST.*;
import AST.CodeGeneration.CodeGenerator;
import AST.Nodes.*;
import AST.SymbolTableFilling.SymbolTableFilling;

public class Compiler implements CompilerConstants {
    public static void main(String[] args) {
        try {
            Compiler compiler = new Compiler(new java.io.FileReader("Compiler/code.txt"));
            Node prog = compiler.prog();

            PrettyPrint prettyPrint = new PrettyPrint();
            SymbolTableFilling symbolTableFilling = new SymbolTableFilling();
            TypeChecking typeChecking = new TypeChecking(symbolTableFilling);
            CodeGenerator codeGenerator = new CodeGenerator(symbolTableFilling);

            prog.accept(prettyPrint);
            System.out.println(prettyPrint.getResult());
            System.out.println();
            System.out.print("Syntax is good");
            prog.accept(symbolTableFilling);
            System.out.println("Symbol table is good");
            prog.accept(typeChecking);
            System.out.println("Type check is good");
            prog.accept(codeGenerator);
            System.out.println("Code generator is good");

            codeGenerator.generateCode();

        } catch (Throwable e) {
            // Catching Throwable is ugly but JavaCC throws Error objects!
            System.out.println("Syntax error: " + e.getMessage());
        }
    }

  final public Node prog() throws ParseException {Prog prog = new Prog();
 Node stmt = null;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INTDCL:
      case FLOATDCL:
      case MULTIPLY:
      case POINTERDCL:
      case IF:
      case BOOLDCL:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      stmt = stmt();
prog.addChild(stmt);
    }
    jj_consume_token(END_OF_FILE);
    jj_consume_token(END_OF_LINE);
{if ("" != null) return prog;}
    throw new Error("Missing return statement in function");
}

  final public Node dcl() throws ParseException {boolean hasExpr = false;
 boolean hasAddress = false;
 boolean isPointer = false;
 Node expr = null;
 Token tAddress = null;
 Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case FLOATDCL:{
      jj_consume_token(FLOATDCL);
      t = jj_consume_token(ID);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ASSIGN:{
        jj_consume_token(ASSIGN);
        expr = expr();
hasExpr = true;
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        ;
      }
if (hasExpr) {
       FloatDcl floatDcl = new FloatDcl(t.image);
       {if ("" != null) return new Assigning(t.image, floatDcl, expr);}
   } else {
       {if ("" != null) return new FloatDcl(t.image);}
   }
      break;
      }
    case INTDCL:{
      jj_consume_token(INTDCL);
      t = jj_consume_token(ID);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ASSIGN:{
        jj_consume_token(ASSIGN);
        expr = expr();
hasExpr = true;
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        ;
      }
if (hasExpr) {
        IntDcl intDcl = new IntDcl(t.image);
        {if ("" != null) return new Assigning(t.image, intDcl, expr);}
    } else {
        {if ("" != null) return new IntDcl(t.image);}
    }
      break;
      }
    case BOOLDCL:{
      jj_consume_token(BOOLDCL);
      t = jj_consume_token(ID);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ASSIGN:{
        jj_consume_token(ASSIGN);
        expr = expr();
hasExpr = true;
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        ;
      }
if (hasExpr) {
        BoolDcl boolDcl = new BoolDcl(t.image);
        {if ("" != null) return new Assigning(t.image, boolDcl, expr);}
    } else {
        {if ("" != null) return new BoolDcl(t.image);}
    }
      break;
      }
    case POINTERDCL:{
      jj_consume_token(POINTERDCL);
      jj_consume_token(MULTIPLY);
      t = jj_consume_token(ID);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ASSIGN:{
        jj_consume_token(ASSIGN);
        jj_consume_token(ADDRESS);
hasAddress = true;
        tAddress = jj_consume_token(ID);
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        ;
      }
if (hasAddress) {
        PointerDcl pointerDcl = new PointerDcl(t.image);
        Id id = new Id(tAddress.image, true, false);
        {if ("" != null) return new Assigning(t.image, pointerDcl, id);}
    } else {
        {if ("" != null) return new PointerDcl(t.image);}
    }
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public Node stmt() throws ParseException {boolean isAddress = false;
    boolean isPointer = false;
    Node ifStmt;
    Node dcl;
    Node expr = null;
    Token t;
    Token tAddress = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case MULTIPLY:
    case ID:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULTIPLY:{
        jj_consume_token(MULTIPLY);
isPointer = true;
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        ;
      }
      t = jj_consume_token(ID);
      jj_consume_token(ASSIGN);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ADDRESS:{
        jj_consume_token(ADDRESS);
        tAddress = jj_consume_token(ID);
isAddress = true;
        break;
        }
      case INT:
      case FLOAT:
      case NOT:
      case TRUE:
      case FALSE:
      case LPAREN:
      case ID:{
        expr = expr();
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(END_OF_LINE);
Id id = new Id(t.image, false, false);
    if (isPointer) {
        id.setPointer(true);
    }
    if (isAddress) {
        Id addressId = new Id(tAddress.image, true, false);
        {if ("" != null) return new Assigning(t.image, id, addressId);}
    }
    {if ("" != null) return new Assigning(t.image, id, expr);}
      break;
      }
    case IF:{
      ifStmt = ifStmt();
{if ("" != null) return ifStmt;}
      break;
      }
    case INTDCL:
    case FLOATDCL:
    case POINTERDCL:
    case BOOLDCL:{
      dcl = dcl();
      jj_consume_token(END_OF_LINE);
{if ("" != null) return dcl;}
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public Node ifStmt() throws ParseException {Node expr;
 Node ifBlock;
 Node elseBlock = null;
 boolean withElse = false;
    jj_consume_token(IF);
    jj_consume_token(LPAREN);
    expr = expr();
    jj_consume_token(RPAREN);
    jj_consume_token(LBRACE);
    ifBlock = block();
    jj_consume_token(RBRACE);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ELSE:{
      jj_consume_token(ELSE);
      jj_consume_token(LBRACE);
      elseBlock = block();
      jj_consume_token(RBRACE);
withElse = true;
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      ;
    }
if (withElse) {
        {if ("" != null) return new IfElse(expr, ifBlock, elseBlock);}
    } else {
        {if ("" != null) return new If(expr, ifBlock);}
    }
    throw new Error("Missing return statement in function");
}

  final public Node block() throws ParseException {Block block = new Block();
   Node stmt = null;
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INTDCL:
      case FLOATDCL:
      case MULTIPLY:
      case POINTERDCL:
      case IF:
      case BOOLDCL:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        break label_2;
      }
      stmt = stmt();
block.addChild(stmt);
    }
{if ("" != null) return block;}
    throw new Error("Missing return statement in function");
}

  final public Node expr() throws ParseException {boolean hasExpr = false;
    Node andTerm;
    Node expr = null;
    Token op = null;
    andTerm = andTerm();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case OR:{
      op = jj_consume_token(OR);
      expr = expr();
hasExpr = true;
      break;
      }
    default:
      jj_la1[11] = jj_gen;
      ;
    }
if (hasExpr) {
        {if ("" != null) return new BinOperator(op.image, andTerm, expr);}
    } else {
        {if ("" != null) return andTerm;}
    }
    throw new Error("Missing return statement in function");
}

  final public Node andTerm() throws ParseException {boolean hasAnd = false;
    Node equalityTerm;
    Node andTerm = null;
    Token op = null;
    equalityTerm = equalityTerm();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case AND:{
      op = jj_consume_token(AND);
      andTerm = andTerm();
hasAnd = true;
      break;
      }
    default:
      jj_la1[12] = jj_gen;
      ;
    }
if (hasAnd) {
        {if ("" != null) return new BinOperator(op.image, equalityTerm, andTerm);}
    } else {
        {if ("" != null) return equalityTerm;}
    }
    throw new Error("Missing return statement in function");
}

  final public Node equalityTerm() throws ParseException {boolean hasEq = false;
    Node relationalTerm;
    Node equalityTerm = null;
    Token op = null;
    relationalTerm = relationalTerm();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case EQ:
    case NE:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case EQ:{
        op = jj_consume_token(EQ);
        break;
        }
      case NE:{
        op = jj_consume_token(NE);
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      equalityTerm = equalityTerm();
hasEq = true;
      break;
      }
    default:
      jj_la1[14] = jj_gen;
      ;
    }
if (hasEq) {
        {if ("" != null) return new BinOperator(op.image, relationalTerm, equalityTerm);}
    } else {
        {if ("" != null) return relationalTerm;}
    }
    throw new Error("Missing return statement in function");
}

  final public Node relationalTerm() throws ParseException {boolean hasTerm = false;
     Node additiveTerm;
     Node relationalTerm = null;
     Token op = null;
    additiveTerm = additiveTerm();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LT:
    case LE:
    case GT:
    case GE:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LT:{
        op = jj_consume_token(LT);
        break;
        }
      case GT:{
        op = jj_consume_token(GT);
        break;
        }
      case GE:{
        op = jj_consume_token(GE);
        break;
        }
      case LE:{
        op = jj_consume_token(LE);
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      relationalTerm = relationalTerm();
hasTerm = true;
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      ;
    }
if (hasTerm) {
        {if ("" != null) return new BinOperator(op.image, additiveTerm, relationalTerm);}
    } else {
        {if ("" != null) return additiveTerm;}
    }
    throw new Error("Missing return statement in function");
}

  final public Node additiveTerm() throws ParseException {boolean hasAdditiveTerm = false;
    Node notTerm;
    Node additiveTerm = null;
    Token op = null;
    notTerm = notTerm();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PLUS:
    case MINUS:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:{
        op = jj_consume_token(PLUS);
        break;
        }
      case MINUS:{
        op = jj_consume_token(MINUS);
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      additiveTerm = additiveTerm();
hasAdditiveTerm = true;
      break;
      }
    default:
      jj_la1[18] = jj_gen;
      ;
    }
if (hasAdditiveTerm) {
        {if ("" != null) return new Computing(op.image, notTerm, additiveTerm);}
    } else {
        {if ("" != null) return notTerm;}
    }
    throw new Error("Missing return statement in function");
}

  final public Node notTerm() throws ParseException {Node factor;
    boolean hasNotTerm = false;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NOT:{
      jj_consume_token(NOT);
hasNotTerm = true;
      break;
      }
    default:
      jj_la1[19] = jj_gen;
      ;
    }
    factor = factor();
if (hasNotTerm) {
        {if ("" != null) return new Not(factor);}
    } else {
        {if ("" != null) return factor;}
    }
    throw new Error("Missing return statement in function");
}

  final public Node factor() throws ParseException {Node val;
    Node expr;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LPAREN:{
      jj_consume_token(LPAREN);
      expr = expr();
      jj_consume_token(RPAREN);
{if ("" != null) return expr;}
      break;
      }
    case INT:
    case FLOAT:
    case TRUE:
    case FALSE:
    case ID:{
      val = val();
{if ("" != null) return val;}
      break;
      }
    default:
      jj_la1[20] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public Node val() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT:{
      t = jj_consume_token(INT);
{if ("" != null) return new IntNum(t.image);}
      break;
      }
    case FLOAT:{
      t = jj_consume_token(FLOAT);
{if ("" != null) return new FloatNum(t.image);}
      break;
      }
    case ID:{
      t = jj_consume_token(ID);
{if ("" != null) return new Id(t.image, false, false);}
      break;
      }
    case TRUE:
    case FALSE:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TRUE:{
        t = jj_consume_token(TRUE);
        break;
        }
      case FALSE:{
        t = jj_consume_token(FALSE);
        break;
        }
      default:
        jj_la1[21] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
{if ("" != null) return new Bool(t.image);}
      break;
      }
    default:
      jj_la1[22] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  /** Generated Token Manager. */
  public CompilerTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[23];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x400e140,0x20000000,0x20000000,0x20000000,0x20000000,0x4004140,0x2000,0x58080280,0x400e140,0x10000,0x400e140,0x40000,0x20000,0x300000,0x300000,0x3c00000,0x3c00000,0x1800,0x1800,0x80000,0x58000280,0x18000000,0x18000280,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x40,0x0,0x0,0x0,0x0,0x0,0x0,0x60,0x40,0x0,0x40,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x40,0x0,0x40,};
	}

  /** Constructor with InputStream. */
  public Compiler(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Compiler(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new CompilerTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 23; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 23; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Compiler(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new CompilerTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 23; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new CompilerTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 23; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Compiler(CompilerTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 23; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(CompilerTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 23; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[39];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 23; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 39; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
